version: "3.9"

services:
  book-store-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
    - "${DB_PORT}:5432"
    volumes:
      - book-store-pgdata:/var/lib/postgresql/data

volumes:
  book-store-pgdata:
    